language: php

php:
  - 5.5
  - 5.6

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e "create database IF NOT EXISTS testing;" -uroot

install:
  - composer install --prefer-source --no-interaction --dev
  - cp .env.example .env

before_script:
  - ./vendor/bin/codecept clean
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run

env:
  - DB_DATABASE_TESTING=testing DB_USERNAME_TESTING=root DB_PASSWORD_TESTING=
