language: php

php:
  - 5.5
  - 5.6

services:
  - mysql

before_install:
  - composer self-update
  - mysql -e "create database IF NOT EXISTS testing;" -uroot
  - mysql -e "create user tester@localhost identified by 'password';" -uroot
  - mysql -e "grant all privileges on testing.* to tester@localhost;" -uroot
  - mysql -e "flush privileges;" -uroot

install:
  - composer install --prefer-source --no-interaction --dev
  - rm -f .env
  - cp .env.travis .env

before_script:
  - ./vendor/bin/codecept clean
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
