language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

before_script:
  - ./vendor/bin/codecept clean
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run unit
